version: 1.0.'{build}'

branches:
  only:
    - master

before_build:
  - set PATH=C:\msys64\mingw64;C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%

build_script:
 - pacman -S mingw64/mingw-w64-x86_64-wget
