version: 1.0.'{build}'

branches:
  only:
    - master

before_build:
  - set PATH=C:\msys64\mingw64;C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%

build_script:
 - pacman --noconfirm -S mingw64/mingw-w64-x86_64-wget
 - mkdir wget
 - copy C:\msys64\mingw64\bin\libassuan-0.dll wget
 - copy C:\msys64\mingw64\bin\libcares-3.dll wget
 - copy C:\msys64\mingw64\bin\libexpat-1.dll wget
 - copy C:\msys64\mingw64\bin\libgpg-error-0.dll wget
 - copy C:\msys64\mingw64\bin\libgpgme-11.dll wget
 - copy C:\msys64\mingw64\bin\libhogweed-4.dll wget
 - copy C:\msys64\mingw64\bin\libiconv-2.dll wget
 - copy C:\msys64\mingw64\bin\libidn2-0.dll wget
 - copy C:\msys64\mingw64\bin\libintl-8.dll wget
 - copy C:\msys64\mingw64\bin\libmetalink-3.dll wget
 - copy C:\msys64\mingw64\bin\libpcre-1.dll wget
 - copy C:\msys64\mingw64\bin\libpsl-5.dll wget
 - copy C:\msys64\mingw64\bin\libunistring-2.dll wget
 - copy C:\msys64\mingw64\bin\libwinpthread-1.dll wget
 - copy C:\msys64\mingw64\bin\wget.exe wget
 - copy C:\msys64\mingw64\bin\zlib1.dll wget
 - 7z a wget.zip wget\*.*
