name: wget

on:
  [push]
jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-20.04
    if: "contains(toJSON(github.event.commits.*.message), '[build wget]')"
    steps:
      - uses: actions/checkout@v2
        name: Checkout project
      - name: Install prerequisites
        run: |
          sudo apt-get install -y mingw-w64 mingw-w64-tools
          sudo apt-get install -y make m4 pkg-config automake gettext
      - name: Build wget 64-bit
        run: |
          x86_64-w64-mingw32-gcc --version
          ./build.sh
      - name: Archive gnutls
        uses: actions/upload-artifact@v1
        with:
          name: wget-1.21.2-64bit-GnuTLS
          path: build-wget-webfolder.io/install/wget-gnutls/wget.exe
      - name: Archive openssl
        uses: actions/upload-artifact@v1
        with:
          name: wget-1.21.2-64bit-OpenSSL
          path: build-wget-webfolder.io/install/wget-openssl/wget.exe
