name: wget

on:
  [push]
jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-20.04
    if: "contains(toJSON(github.event.commits.*.message), '[build wget x86]')"
    steps:
      - uses: actions/checkout@v2
        name: Checkout project
      - name: Install prerequisites
        run: |
          sudo apt-get install -y mingw-w64-i686-dev mingw-w64-tools mingw-w64
          sudo apt-get install -y make m4 pkg-config automake gettext
      - name: Build wget 32-bit
        run: |
          i686-w64-mingw32-gcc --version
          ./build-x86.sh
      - name: Archive library gnutls
        uses: actions/upload-artifact@v1
        with:
          name: wget-1.21.2-32bit-GnuTLS
          path: build-wget-webfolder.io-x86/install/wget-gnutls/wget.exe
      - name: Archive library openssl
        uses: actions/upload-artifact@v1
        with:
          name: wget-1.21.2-32bit-OpenSSL
          path: build-wget-webfolder.io-x86/install/wget-openssl/wget.exe
